version: '3.8'

services:
  user-management:
      image: ayulanka.azurecr.io/ayulanka/user-management:latest
      build: ./userManagement
      ports:
        - 3001:3001
      environment:
        - MONGODB_URL=${MONGODB_URL}

  product-management:
      image: ayulanka.azurecr.io/ayulanka/product-management:latest
      build: ./productManagement
      ports:
        - 3002:3002
      environment:
        - MONGODB_URL=${MONGODB_URL}

  order-management:
      image: ayulanka.azurecr.io/ayulanka/order-management:latest
      build: ./productCheckoutManagement
      ports:
        - 3005:3005
      environment:
        - MONGODB_URL=${MONGODB_URL}

  payment-management:
      image: ayulanka.azurecr.io/ayulanka/payment-management:latest
      build: ./paymentManagmenet
      ports:
        - 3007:3007
      environment:
        - MONGODB_URL=${MONGODB_URL}

  cart-management:
      image: ayulanka.azurecr.io/ayulanka/cart-management:latest
      build: ./cartManagement
      ports:
        - 3006:3006
      environment:
        - MONGODB_URL=${MONGODB_URL}

  seller-management:
      image: ayulanka.azurecr.io/ayulanka/seller-management:latest
      build: ./sellerManagement
      ports:
        - 3004:3004
      environment:
        - MONGODB_URL=${MONGODB_URL}
        - CLOUD_NAME=${CLOUD_NAME}
        - CLOUD_KEY=${CLOUD_KEY}
        - CLOUD_KEY_SECRET=${CLOUD_KEY_SECRET}
        - TOKEN_KEY=${TOKEN_KEY}
        - EMAIL_API_KEY=${EMAIL_API_KEY}
        - EMAIL_SECRET_KEY=${EMAIL_SECRET_KEY}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - user-management
      - product-management
      - payment-management
      - order-management
      - cart-management
      - seller-management
    restart: always

  ayulanka-web:
      image: ayulanka.azurecr.io/ayulanka/ayulanka-web:latest
      build: ./ayulanka-web
      ports:
        - 3000:3000
      environment:
        - REACT_APP_API_URL=http://nginx/
      depends_on:
        - nginx

volumes:
  mongodb_data:
