# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ayu-user

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ayulanka.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9355ddbf218a446d97ba9cefb59301e2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9d8c37fd714e47e58ea55760a610da05 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ayulanka.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9355ddbf218a446d97ba9cefb59301e2 }}/user-management:${{ github.sha }}
        context: ./userManagement/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ayu-user'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_37c36af003c74a8485821f22050ef8b5 }}
        images: 'ayulanka.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9355ddbf218a446d97ba9cefb59301e2 }}/user-management:${{ github.sha }}'